package com.efjpr.rejob.domain.Enums;

public enum EducationLevel {
    ENSINO_FUNDAMENTAL_COMPLETO,
    ENSINO_FUNDAMENTAL_INCOMPLETO,
    ENSINO_MEDIO_COMPLETO,
    ENSINO_MEDIO_INCOMPLETO,
    EDUCACAO_SUPERIOR_COMPLETA,
    EDUCACAO_SUPERIOR_INCOMPLETA,
    POS_GRADUACAO_COMPLETA,
    POS_GRADUACAO_INCOMPLETA,
    MESTRADO_COMPLETO,
    MESTRADO_INCOMPLETO,
    DOUTORADO_COMPLETO,
    DOUTORADO_INCOMPLETO,
    OUTRO;
}
