CREATE TABLE Job (
                     id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                     companyLocation VARCHAR(255),
                     jobType VARCHAR(255),
                     categories VARCHAR(255),
                     contactPerson_id BIGINT,
                     jobTitle VARCHAR(255),
                     requirements VARCHAR(255),
                     jobDescription VARCHAR(255),
                     benefits VARCHAR(255),
                     employmentType VARCHAR(255),
                     applicationDeadline TIMESTAMP,
                     jobStatus VARCHAR(20),
                     FOREIGN KEY (contactPerson_id) REFERENCES collaborators(id)
);
