-- liquibase formatted sql

-- Changeset pedro.tenorio:create companies and add fk to collaboratos


CREATE TABLE companies (
                           id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                           cnpj VARCHAR(255),
                           business_activity VARCHAR(255),
                           number_of_employees INTEGER,
                           headquarters VARCHAR(255),
                           phone VARCHAR(255),
                           institutional_description VARCHAR(255)
);




ALTER TABLE Collaborators
    ADD COLUMN company_id BIGINT,
    ADD CONSTRAINT fk_company
        FOREIGN KEY (company_id)
            REFERENCES companies (id);

