--liquibase formatted sql

--changeset pedro_tenorio:1

CREATE TABLE users (
                       id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                       name VARCHAR(255),
                       role VARCHAR(50),
                       email VARCHAR(255) UNIQUE NOT NULL,
                       password VARCHAR(255) NOT NULL,
                       phone_number VARCHAR(20),
                       created_date TIMESTAMP,
                       last_updated_date TIMESTAMP
);

CREATE TABLE employees (
                           id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                           user_id BIGINT UNIQUE,
                           cpf VARCHAR(20),
                           prison_code VARCHAR(255),
                           education_level VARCHAR(255),
                           date_of_birth VARCHAR(20),
                           residence_location VARCHAR(255),
                           sentence_regime VARCHAR(50),
                           professional_experience VARCHAR(255),
                           areas_of_interest VARCHAR(255),
                           skills_and_qualifications VARCHAR(255),
                           educational_history VARCHAR(255),
                           FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE collaborators (
                               id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                               user_id BIGINT UNIQUE,
                               job_title VARCHAR(255),
                               department_or_area VARCHAR(255),
                               collaborator_type VARCHAR(50),
                               FOREIGN KEY (user_id) REFERENCES users(id)
);
