FROM node:16-alpine as build-stage

WORKDIR /app

COPY package*.json ./

RUN npm install redux-persist

RUN npm install


COPY . .


RUN npm run build

FROM nginx:alpine as production-stage

COPY --from=build-stage /app/build /usr/share/nginx/html
COPY ./nginx.conf /etc/nginx/nginx.conf

EXPOSE 80

ENTRYPOINT ["nginx", "-g", "daemon off;"]
