FROM node:16-alpine as build-stage

WORKDIR /app

COPY . .

RUN npm install
RUN npm run build

FROM nginx:alpine as production-stage

COPY --from=build-stage /app/build /usr/share/nginx/html

EXPOSE 80

ENTRYPOINT ["nginx", "-g", "daemon off;"]
